language:
- java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- "./gradlew assemble -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_PASS"
script:
- "./gradlew check -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_PASS"
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER
  -PbintrayApiKey=$BINTRAY_PASS; fi
env:
  global:
  - secure: BazmN4DpQNBqMCPKxC1QgFwFYJc41WwD3TG5mLT3Rg6AJlFO3McsjiDnc8/PJIACqaOtEPfcclvvUmQuTRVguZ5pnQWrQvKlxxcslmWB+QIYP9BD2KRoGgPob0Y/V8RCveWd4HzptDP6wqnIBEHphj/yGfAO6RJpw8PLId+4Dt4hRv2NRE4b21MKueKJj/+8Kg7SocNDSwLVLqExa4vZNSLwFod3ws2Q10iXmDVw3FvH1qV1p0SwKq+34cKTt3SXccD/oy6EIKSEo9dsZqpKXw8miGRfZiiwYG1I72nbYmFDxqRGj0SfzjzFmNsRs4NoKgqyBSQ28Qca6a1ceNmqtVOn1AA09HiUKTmzg/WZrKxWXVjDOd8S4BUVmRcq2ONkkiBw7GT2Hv80X8uyoBtH4MNsLr0c2j4Kd+lA7nABdXLrwqL6KN2zeAhyXWmQ+xQuvXQV7tweBusuKh5ATqut5+iro24aUmPicfmOEz9N4itatYXV9U9r165QPhR4kDufP4zMlcfx5iztneNIXvQb1WsqEXCX2onVkjLqpVF1nXBTQttyQnzOssx/ACW3VJrMK7uuOWMHp4H/nVg3a4J6O950RGhugUDpJYE/PBAkCuXcochv3BJdz5bgr+/OB8uBsdq/l6+JruJY1PQDntVO0TAU5UhO7iOUjuCiR21zoCw=
  - secure: l6X7sHGQywSA45GVD/DXcdj0U73fGBYvyfiDNu8TUqCTYBuWAacVWYTkhenx04/0XwEdWta55XF6bBS0coPapRMsd8rOHQjSZBXA+CpxMCzS2bIMLwavmiFFqM2LyiUZZFjh/VkWK3428UCwM4nzgNUszwhB2Brxj0KbkU21j7tINE7mo4LzTekyEuUe3cWUYINSENk77HJkXjE+Tp4e1g/ArUEcdUiGJEAV2HdvlJ0pGGD9ioHJCzJt2jSAEgKgnVgGhutxDZYA5VhLanjzUq2D73YZ9UgB8iVyOrekWa7fKqewvMtr37d/yIy6WmhIe7dw+erTS6MK3XqzFEACpjJvGMD6bhuBLtbA7wlBjR8JFz7Zdez+n86WIrc4WZrans3eyo9FIJdzloELsj9FE2VVlm1q0gxKXDyPrt15b7TDJHS61RHX/g9zKB7GXmwsmk50y5p0UE1dRKknntGs5oNFmFHSrkB9loSMR93cEVs7LNQ5IRnSDuP+cYB88Pj6VZ303EvPNRVh7VKlXfOieahEt/FK/FUAvGoFDrjR3rtyauBSEr/q+ocBoSXxIA1ZgmpbCsK2lzAvt3dZl2H6FP8Ca924bvZ+OQfT3lN1JI2nEhw0EXf21NuXp7Jcqr6ua6DzoKeXIj0NMjRDOo8hpcPmxq4wHBPmjPQGdSU1pqE=
